---
title: Something

datasources:
  twitter:
    plugin: twitter
    args:
      consumer_key: ${TWITTER_CONSUMER_KEY}
      consumer_secret: ${TWITTER_CONSUMER_SECRET}
      # access_token_key: ${TWITTER_ACCESS_TOKEN_KEY}
      # access_token_secret: ${TWITTER_ACCESS_TOKEN_SECRET}

views:
  tweets:
    plugin: twitter.engagement
    args:
      datasource: twitter
      query_args:
        username: POTUS
